### ISSUE TITLE
api: switch from JSON data type to ARROW IPC

### ISSUE THREAD

**Issue by rampage644** [Embucket/embucket-labs#115]
[Branch](https://github.com/Embucket/control-plane-v2/tree/issues/115_switch_to_arrow_ipc)

Snowflake converter for FIXED datatype via arrow ipc natively supports: int8, int16, int32, int64, DECIMAL128 and no uint types at all:
https://github.com/snowflakedb/snowflake-connector-python/blob/main/src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowChunkIterator.cpp#L173

**Comment by YaroslavLitvinov** [comment]
It's possible that resolving this issue will fix another issue #67.

**Comment by YaroslavLitvinov** [comment]
Enabling arrow format causes errors on connector's side.
`Failed to convert current row, cause: [Snowflake Exception] unknown arrow internal data type(260913075) for FIXED data`

**Comment by YaroslavLitvinov** [comment]
Following data snippet (in `data` variable) causes above error ^^ in snowflake connector, when
being returned as a part of response in `rowSetBase64` field. 
Also the same data snipped parsed without errors in a code below, by pyarrow library version 19.0, which is the same version is used in snowflake connector in my environment.

Parsed result :
```
pyarrow.Table
count: uint64 not null
----
count: [[0]]
```

Code:
```
import base64
import pyarrow
from pyarrow import RecordBatchStreamReader  # NOQA
from pyarrow import RecordBatch, RecordBatchStreamWriter

def read_arrrow_base_64(data):
    decoded_data = base64.b64decode(data)
    reader = RecordBatchStreamReader(decoded_data)
    return reader.read_all()

data = "/////ygBAAAQAAAAAAAKAAwACgAJAAQACgAAABAAAAAAAQQACAAIAAAABAAIAAAABAAAAAEAAAAYAAAAAAASABoAFAAAABMACAAAAAwABAASAAAANAAAABgAAAAcAAAAAAAAAhgAAAAAAAYACAAEAAYAAABAAAAAAAAAAAUAAABjb3VudAAAAAQAAACAAAAAUAAAACwAAAAEAAAAmP///wgAAAAMAAAAAQAAADAAAAAKAAAAY2hhckxlbmd0aAAAvP///wgAAAAMAAAAAQAAADAAAAAFAAAAc2NhbGUAAADc////CAAAAAwAAAABAAAANgAAAAsAAABsb2dpY2FsVHlwZQAIAAwACAAEAAgAAAAIAAAADAAAAAIAAAAzOAAACQAAAHByZWNpc2lvbgAAAP////+IAAAAEAAAAAwAGgAYABcABAAIAAwAAAAgAAAAEAAAAAAAAAAAAAAAAAAAAwQACgAYAAwACAAEAAoAAAAsAAAAEAAAAAEAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAEAAAAAAAAACAAAAAAAAAAIAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAD/////AAAAAA=="

print(read_arrrow_base_64(data))
```

**Comment by YaroslavLitvinov** [comment]
Embucket supports different set of datatypes than [Snowflake do](https://docs.snowflake.com/en/sql-reference/intro-summary-data-types)

Snowflake’s support of FIXED types is pretty limited, no unsigned types supported at all, like Uint64. Respectively Snowflake’s connector expects following signed types: int8, int16, int32, int64, decimal128.
In count batch response replacing UInt64 by Int64 fixes issue.

**Comment by YaroslavLitvinov** [comment]
There is an issue showing how crucial could be having a right alignment:
https://github.com/apache/arrow-rs/issues/5052

**Comment by YaroslavLitvinov** [comment]
Testing with dbt showed yet another bug in arrow support, when `dbt seed` is running following query 
``` sql
select all_objects.*, is_iceberg
      from table(result_scan(last_query_id(-1))) all_objects
      left join INFORMATION_SCHEMA.tables as all_tables
        on all_tables.table_name = all_objects."name"
        and all_tables.table_schema = all_objects."schema_name"
        and all_tables.table_catalog = all_objects."database_name"
```
it causes an error on client:
```
    _next = self.fetchone()
  File "venv/lib/python3.13/site-packages/snowflake/connector/cursor.py", line 1485, in fetchone
    _next = next(self._result, None)
  File "venv/lib/python3.13/site-packages/snowflake/connector/result_set.py", line 97, in result_set_iterator
    yield from first_batch_iter
  File "src/snowflake/connector/nanoarrow_cpp/ArrowIterator/nanoarrow_arrow_iterator.pyx", line 173, in snowflake.connector.nanoarrow_arrow_iterator.PyArrowRowIterator.__next__
IndexError: _Map_base::at
```

parsed RecordBatch  using pyarrow:
```
Table.schema:
database_name: string not null
  -- field metadata --
  scale: '0'
  logicalType: 'TEXT'
  charLength: '16777216'
  precision: '38'
schema_name: string not null
  -- field metadata --
  scale: '0'
  logicalType: 'TEXT'
  precision: '38'
  charLength: '16777216'
name: string not null
  -- field metadata --
  precision: '38'
  charLength: '16777216'
  logicalType: 'TEXT'
  scale: '0'
kind: string not null
  -- field metadata --
  charLength: '16777216'
  precision: '38'
  logicalType: 'TEXT'
  scale: '0'
comment: null
  -- field metadata --
  precision: '38'
  scale: '0'
  charLength: '0'
  logicalType: 'NULL'
is_iceberg: string not null
  -- field metadata --
  charLength: '16777216'
  logicalType: 'TEXT'
  precision: '38'
  scale: '0'
is_dynamic: string not null
  -- field metadata --
  logicalType: 'TEXT'
  charLength: '16777216'
  precision: '38'
  scale: '0' 

[pyarrow.RecordBatch
database_name: string not null
schema_name: string not null
name: string not null
kind: string not null
comment: null
is_iceberg: string not null
is_dynamic: string not null
----
database_name: ["snowplow"]
schema_name: ["public2"]
name: ["events_iceberg"]
kind: ["TABLE"]
comment: 1 nulls
is_iceberg: ["Y"]
is_dynamic: ["N"], pyarrow.RecordBatch
database_name: string not null
schema_name: string not null
name: string not null
kind: string not null
comment: null
is_iceberg: string not null
is_dynamic: string not null
----
database_name: ["snowplow"]
schema_name: ["information_schema"]
name: ["tables"]
kind: ["VIEW"]
comment: 1 nulls
is_iceberg: ["N"]
is_dynamic: ["N"], pyarrow.RecordBatch
database_name: string not null
schema_name: string not null
name: string not null
kind: string not null
comment: null
is_iceberg: string not null
is_dynamic: string not null
----
database_name: ["datafusion","snowplow"]
schema_name: ["information_schema","information_schema"]
name: ["df_settings","schemata"]
kind: ["VIEW","VIEW"]
comment: 2 nulls
is_iceberg: ["N","N"]
is_dynamic: ["N","N"], pyarrow.RecordBatch
database_name: string not null
schema_name: string not null
name: string not null
kind: string not null
comment: null
is_iceberg: string not null
is_dynamic: string not null
----
database_name: ["datafusion"]
schema_name: ["information_schema"]
name: ["schemata"]
kind: ["VIEW"]
comment: 1 nulls
is_iceberg: ["N"]
is_dynamic: ["N"]]
```
